<?$APPLICATION->IncludeComponent(
	"bitrix:search.title",
	"inheader",
	Array(
		"CATEGORY_0" => array("no"),
		"CATEGORY_0_TITLE" => "",
		"CHECK_DATES" => "N",
		"CONTAINER_ID" => "title-search",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"IBLOCK_ID" => array("24"),
		"INPUT_ID" => "title-search-input",
		"NUM_CATEGORIES" => "1",
		"OFFERS_FIELD_CODE" => array("NAME","PREVIEW_PICTURE",""),
		"OFFERS_PROPERTY_CODE" => array("","CML2_LINK",""),
		"OPEN_INPUT" => "N",
		"ORDER" => "date",
		"PAGE" => "/search/",
		"PRICE_CODE" => array("BASE"),
		"PRICE_VAT_INCLUDE" => "N",
		"PRODUCT_QUANTITY_VARIABLE" => "quan",
		"SHOW_INPUT" => "Y",
		"SHOW_OTHERS" => "N",
		"TOP_COUNT" => "5",
		"USE_LANGUAGE_GUESS" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"START_HIDDEN" => "Y",
		"SHOW_SEARCHBAR" => "Y",
		"JS_OPENER" => "Y",
		"JS_OPENER_MOBILE" => "N",
	)
);?>
