<?php
if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
    die();

use \Bitrix\Main\Localization\Loc;

Loc::loadMessages(__FILE__);

return array(
    'TABS' => array(
        'TAB_GOPRO' => array(
            'NAME' => Loc::getMessage('RS.GOPRO.TAB_GOPRO.NAME'),
        ),
    ),
    'PARAMETERS' => array(
        'TITLE_COLORS' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'TITLE',
            'NAME' => Loc::getMessage('RS.GOPRO.TITLE.COLORS'),
            'GRID_SIZE' => 12,
        ),
        'COLOR' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'COLORPICKER',
            'NAME' => Loc::getMessage('RS.GOPRO.COLOR'),
            'CONTROL_ID' => 'color',
            'CONTROL_NAME' => 'color',
            'GRID_SIZE' => 12,
            'CSS_CLASS' => '',
            'ATTR' => '',
            'MULTIPLE' => 'Y',
            'VALUES' => array(
                'COLOR_1' => array(
                    'NAME' => Loc::getMessage('RS.GOPRO.COLOR__1'),
                    'CONTROL_ID' => 'color1',
                    'CONTROL_NAME' => 'color1',
                    'HTML_VALUE' => 'aabf6b',
                    'DEFAULT' => 'aabf6b',
                    'MACROS' => 'COLOR_1_1',
                ),
                'COLOR_2' => array(
                    'NAME' => Loc::getMessage('RS.GOPRO.COLOR__2'),
                    'CONTROL_ID' => 'color2',
                    'CONTROL_NAME' => 'color2',
                    'HTML_VALUE' => 'fed85e',
                    'DEFAULT' => 'fed85e',
                    'MACROS' => 'COLOR_1_2',
                ),
            ),
            'SETS' => array(
                'NAME' => Loc::getMessage('RS.GOPRO.SETS'),
                'VALUES' => array(
                    'SET_1' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'kids',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#36acd4',
                        'VALUES' => array(
                            'COLOR_1' => '36acd4',
                            'COLOR_2' => 'fed75e',
                        ),
                    ),
                    'SET_2' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'animal',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#e9c440',
                        'VALUES' => array(
                            'COLOR_1' => 'e9c440',
                            'COLOR_2' => 'ee3523',
                        ),
                    ),
                    'SET_3' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'sport',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#5d640b',
                        'VALUES' => array(
                            'COLOR_1' => '5d640b',
                            'COLOR_2' => 'b7af4d',
                        ),
                    ),
                    'SET_4' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'office',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#214496',
                        'VALUES' => array(
                            'COLOR_1' => '214496',
                            'COLOR_2' => 'ee3523',
                        ),
                    ),
                    'SET_5' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'house',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#926d66',
                        'VALUES' => array(
                            'COLOR_1' => '926d66',
                            'COLOR_2' => '6b80a0',
                        ),
                    ),
                    'SET_6' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'build',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#c4010c',
                        'VALUES' => array(
                            'COLOR_1' => 'c4010c',
                            'COLOR_2' => '6b80a0',
                        ),
                    ),
                    'SET_7' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'fashion',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#9375ab',
                        'VALUES' => array(
                            'COLOR_1' => '9375ab',
                            'COLOR_2' => 'bdd179',
                        ),
                    ),
                    'SET_8' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'casa',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#574527',
                        'VALUES' => array(
                            'color1' => '574527',
                            'COLOR_2' => '3c5582',
                        ),
                    ),
                    'SET_9' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'market',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#aabf6b',
                        'VALUES' => array(
                            'COLOR_1' => 'aabf6b',
                            'COLOR_2' => 'fed85e',
                        ),
                    ),
                    'SET_10' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'auto',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#4c6ca5',
                        'VALUES' => array(
                            'COLOR_1' => '4c6ca5',
                            'COLOR_2' => '8cba25',
                        ),
                    ),
                    'SET_11' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'opt',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#ee8131',
                        'VALUES' => array(
                            'COLOR_1' => 'ee8131',
                            'COLOR_2' => '899CC7',
                        ),
                    ),
                    'SET_12' => array(
                        'NAME' => '',
                        'CONTROL_ID' => 'gmarket',
                        'CONTROL_NAME' => '',
                        'BACKGROUND' => '#e70b43',
                        'VALUES' => array(
                            'COLOR_1' => 'e70b43',
                            'COLOR_2' => '333333',
                        ),
                    ),
                ),
            ),
        ),
        'TITLE_HEADER_SETTINGS' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'TITLE',
            'NAME' => Loc::getMessage('RS.GOPRO.TITLE.HEADER_SETTINGS'),
            'GRID_SIZE' => 12,
        ),
        'HEADER_TYPE' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'RADIO',
            'NAME' => Loc::getMessage('RS.GOPRO.HEADER_TYPE.TYPE'),
            'GRID_SIZE' => 12,
            'CONTROL_NAME' => 'header_type',
            'DEFAULT' => 'type1',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
            'VALUES' => array(
                'HEADER_1' => array(
                    'NAME' => Loc::getMessage('RS.GOPRO.HEADER_TYPE.TYPE_1'),
                    'CONTROL_ID' => 'header_type_1',
                    'HTML_VALUE' => 'type1',
                ),
                'HEADER_2' => array(
                    'NAME' => Loc::getMessage('RS.GOPRO.HEADER_TYPE.TYPE_2'),
                    'CONTROL_ID' => 'header_type_2',
                    'HTML_VALUE' => 'type2',
                ),
            ),
            'VIEW' => 'buttons',
        ),
        'SWITCH_USE_HEADER_FLY' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'SWITCH',
            'NAME' => Loc::getMessage('RS.GOPRO.USE_HEADER_FLY'),
            'GRID_SIZE' => 12,
            'CONTROL_ID' => 'switch_use_header_fly',
            'CONTROL_NAME' => 'switch_use_header_fly',
            'HTML_VALUE' => 'Y',
            'DEFAULT' => 'Y',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
        ),
        'TITLE_MAIN_MENU_TYPE' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'TITLE',
            'NAME' => Loc::getMessage('RS.GOPRO.TITLE.MAIN_MENU_TYPE'),
            'GRID_SIZE' => 12,
        ),
        'MAIN_MENU_TYPE' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'RADIO',
            'NAME' => '',
            'GRID_SIZE' => 12,
            'CONTROL_NAME' => 'main_menu_type',
            'DEFAULT' => 'horizontal1',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
            'VALUES' => array(
                'HTYPE_1' => array(
                    'NAME' => Loc::getMessage('RS.GOPRO.MAIN_MENU_TYPE.VERTICAL_1'),
                    'CONTROL_ID' => 'main_menu_type_1',
                    'HTML_VALUE' => 'vertical1',
                    'IMAGE' => '/include/tuning/img/gopro1.png',
                ),
                'HTYPE_2' => array(
                    'NAME' => Loc::getMessage('RS.GOPRO.MAIN_MENU_TYPE.VERTICAL_2'),
                    'CONTROL_ID' => 'main_menu_type_2',
                    'HTML_VALUE' => 'vertical2',
                    'IMAGE' => '/include/tuning/img/gopro2.png',
                ),
                'HTYPE_3' => array(
                    'NAME' => Loc::getMessage('RS.GOPRO.MAIN_MENU_TYPE.HORIZONTAL_1'),
                    'CONTROL_ID' => 'main_menu_type_3',
                    'HTML_VALUE' => 'horizontal1',
                    'IMAGE' => '/include/tuning/img/gopro3.png',
                ),
            ),
            'HIDE_LABELS' => 'Y',
            'VIEW' => 'images',
            'GRID_SIZE_VALUE' => 4,
        ),
        'TITLE_MAIN_BLOCKS' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'TITLE',
            'NAME' => Loc::getMessage('RS.GOPRO.TITLE.MAIN_BLOCKS'),
            'GRID_SIZE' => 12,
        ),
        'SWITCH_FICHI' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'SWITCH',
            'NAME' => Loc::getMessage('RS.GOPRO.SWITCH.FICHI'),
            'GRID_SIZE' => 6,
            'CONTROL_ID' => 'switch_fichi',
            'CONTROL_NAME' => 'switch_fichi',
            'HTML_VALUE' => 'Y',
            'DEFAULT' => 'Y',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
        ),
        'SWITCH_NEWS_AND_SECTIONS' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'SWITCH',
            'NAME' => Loc::getMessage('RS.GOPRO.SWITCH.NEWS_AND_SECTIONS'),
            'GRID_SIZE' => 6,
            'CONTROL_ID' => 'switch_news_and_sections',
            'CONTROL_NAME' => 'switch_news_and_sections',
            'HTML_VALUE' => 'Y',
            'DEFAULT' => 'Y',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
        ),
        'SWITCH_BEST_PRODUCTS' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'SWITCH',
            'NAME' => Loc::getMessage('RS.GOPRO.SWITCH.BEST_PRODUCTS'),
            'GRID_SIZE' => 6,
            'CONTROL_ID' => 'switch_best_products',
            'CONTROL_NAME' => 'switch_best_products',
            'HTML_VALUE' => 'Y',
            'DEFAULT' => 'Y',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
        ),
        'SWITCH_GALLERY' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'SWITCH',
            'NAME' => Loc::getMessage('RS.GOPRO.SWITCH.GALLERY'),
            'GRID_SIZE' => 6,
            'CONTROL_ID' => 'switch_gallery',
            'CONTROL_NAME' => 'switch_gallery',
            'HTML_VALUE' => 'Y',
            'DEFAULT' => 'Y',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
        ),
        'SWITCH_BRANDS' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'SWITCH',
            'NAME' => Loc::getMessage('RS.GOPRO.SWITCH.BRANDS'),
            'GRID_SIZE' => 6,
            'CONTROL_ID' => 'switch_brands',
            'CONTROL_NAME' => 'switch_brands',
            'HTML_VALUE' => 'Y',
            'DEFAULT' => 'Y',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
        ),
        'SWITCH_SHOPS' => array(
            'TAB' => 'TAB_GOPRO',
            'TYPE' => 'SWITCH',
            'NAME' => Loc::getMessage('RS.GOPRO.SWITCH.SHOPS'),
            'GRID_SIZE' => 6,
            'CONTROL_ID' => 'switch_shops',
            'CONTROL_NAME' => 'switch_shops',
            'HTML_VALUE' => 'Y',
            'DEFAULT' => 'Y',
            'CSS_CLASS' => '',
            'ATTR' => '',
            'RELOAD' => 'Y',
        ),
    ),
);
